import {
  FaDatabase,
  FaCode,
  FaRobot,
  FaBrain,
  FaCube,
  FaShieldAlt,
  FaCloud,
  FaMobileAlt,
  FaGamepad,
  FaPencilRuler,
  FaBullhorn,
  FaPenNib,
  FaPaintBrush,
  FaVideo,
  FaCamera,
  FaMusic,
  FaFilm,
  FaShapes,
  FaVrCardboard,
  FaGlasses,
} from "react-icons/fa";
const skillsDetails = [
  { name: "Data Science", icon: <FaDatabase /> },
  { name: "Web Development", icon: <FaCode /> },
  { name: "Machine Learning", icon: <FaRobot /> },
  { name: "AI", icon: <FaBrain /> },
  { name: "Blockchain", icon: <FaCube /> },
  { name: "Cyber Security", icon: <FaShieldAlt /> },
  { name: "Cloud Computing", icon: <FaCloud /> },
  { name: "Mobile Development", icon: <FaMobileAlt /> },
  { name: "Game Development", icon: <FaGamepad /> },
  { name: "UI/UX Design", icon: <FaPencilRuler /> },
  { name: "Digital Marketing", icon: <FaBullhorn /> },
  { name: "Content Writing", icon: <FaPenNib /> },
  { name: "Graphic Design", icon: <FaPaintBrush /> },
  { name: "Video Editing", icon: <FaVideo /> },
  { name: "Photography", icon: <FaCamera /> },
  { name: "Music Production", icon: <FaMusic /> },
  { name: "Animation", icon: <FaFilm /> },
  { name: "3D Modeling", icon: <FaShapes /> },
  { name: "Virtual Reality", icon: <FaVrCardboard /> },
  { name: "Augmented Reality", icon: <FaGlasses /> },
];
export default skillsDetails;
